AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - bin/*

Style/AccessorGrouping:
  EnforcedStyle: separated

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Enabled: false
